<?php
/**
 * ACF: Page templates (Antrenori, Despre, Campioni, Orar, Tarife, Discipline, Galerie)
 *
 * @package Kokoro
 */

defined('ABSPATH') || exit;

function kokoro_acf_register_page_templates() {
    if (!function_exists('acf_add_local_field_group')) return;

    acf_add_local_field_group([
        'key'    => 'group_kokoro_pagina_antrenori',
        'title'  => 'Conținut pagina Antrenori',
        'fields' => [
            [
                'key'           => 'field_antr_hero_titlu',
                'label'         => 'Titlu hero',
                'name'          => 'antr_hero_titlu',
                'type'          => 'text',
                'default_value' => 'ECHIPA|KOKORO',
            ],
            [
                'key'           => 'field_antr_hero_subtitlu',
                'label'         => 'Subtitlu hero',
                'name'          => 'antr_hero_subtitlu',
                'type'          => 'textarea',
                'rows'          => 3,
                'default_value' => 'Antrenori cu zeci de ani de experiență, dedicați să formeze caractere puternice și sportivi de top.',
            ],
            [
                'key'           => 'field_antr_jp_kanji',
                'label'         => 'Citat — kanji',
                'name'          => 'antr_jp_kanji',
                'type'          => 'text',
                'default_value' => '「先生」',
            ],
            [
                'key'           => 'field_antr_jp_romaji',
                'label'         => 'Citat — romaji',
                'name'          => 'antr_jp_romaji',
                'type'          => 'text',
                'default_value' => 'Sensei',
            ],
            [
                'key'           => 'field_antr_jp_traducere',
                'label'         => 'Citat — traducere',
                'name'          => 'antr_jp_traducere',
                'type'          => 'text',
                'default_value' => 'Cel care a mers înaintea ta — învățătorul, mentorul.',
            ],
            [
                'key'           => 'field_antr_cta_titlu',
                'label'         => 'Titlu CTA jos',
                'name'          => 'antr_cta_titlu',
                'type'          => 'text',
                'default_value' => 'ANTRENEAZĂ-TE CU|CEI MAI BUNI',
            ],
            [
                'key'           => 'field_antr_cta_text',
                'label'         => 'Text CTA',
                'name'          => 'antr_cta_text',
                'type'          => 'textarea',
                'rows'          => 2,
                'default_value' => 'Vino la o lecție demonstrativă gratuită și cunoaște echipa Kokoro.',
            ],
        ],
        'location' => [
            [['param' => 'page_template', 'operator' => '==', 'value' => 'page-antrenori.php']],
        ],
        'menu_order' => 0,
        'position'   => 'normal',
        'style'      => 'default',
        'label_placement' => 'top',
        'active'     => true,
    ]);

    acf_add_local_field_group([
        'key'    => 'group_kokoro_pagina_despre',
        'title'  => 'Conținut pagina Despre Noi',
        'fields' => [
            ['key' => 'field_d_tab_hero', 'label' => 'HERO', 'type' => 'tab', 'placement' => 'left'],
            ['key' => 'field_d_hero_titlu',    'name' => 'despre_hero_titlu',    'label' => 'Titlu hero',    'type' => 'text',     'default_value' => 'DESPRE|KOKORO'],
            ['key' => 'field_d_hero_subtitlu', 'name' => 'despre_hero_subtitlu', 'label' => 'Subtitlu hero', 'type' => 'textarea', 'rows' => 3, 'default_value' => 'O academie de Ju-Jitsu fondată din pasiune. Fiecare antrenament e un pas spre versiunea ta mai bună.'],
            ['key' => 'field_d_hero_imagine',  'name' => 'despre_hero_imagine',  'label' => 'Imagine hero (opțional)', 'type' => 'image', 'return_format' => 'url', 'preview_size' => 'medium'],

            ['key' => 'field_d_tab_poveste', 'label' => 'POVESTEA', 'type' => 'tab', 'placement' => 'left'],
            ['key' => 'field_d_poveste_titlu',   'name' => 'despre_poveste_titlu',   'label' => 'Titlu',    'type' => 'text', 'default_value' => 'POVESTEA|NOASTRĂ'],
            ['key' => 'field_d_poveste_text',    'name' => 'despre_poveste_text',    'label' => 'Text',     'type' => 'wysiwyg', 'tabs' => 'visual', 'toolbar' => 'basic', 'media_upload' => 0, 'default_value' => 'În 2008, Sensei Lucică a deschis primul dojo Kokoro Brașov cu ambiția de a forma sportivi de elită și caractere puternice. De atunci, sute de copii, juniori și adulți au trecut prin sala noastră, iar zeci au cucerit medalii la competiții naționale și internaționale.'],
            ['key' => 'field_d_poveste_imagine', 'name' => 'despre_poveste_imagine', 'label' => 'Imagine',  'type' => 'image', 'return_format' => 'url', 'preview_size' => 'medium'],

            ['key' => 'field_d_tab_mv', 'label' => 'MISIUNE & VIZIUNE', 'type' => 'tab', 'placement' => 'left'],
            ['key' => 'field_d_misiune_titlu', 'name' => 'despre_misiune_titlu', 'label' => 'Titlu Misiune',  'type' => 'text',     'default_value' => 'MISIUNE'],
            ['key' => 'field_d_misiune_text',  'name' => 'despre_misiune_text',  'label' => 'Text Misiune',   'type' => 'textarea', 'rows' => 4, 'default_value' => 'Să formăm sportivi puternici, disciplinați și respectuoși, transmițând tradiția Ju-Jitsu prin antrenamente de calitate.'],
            ['key' => 'field_d_viziune_titlu', 'name' => 'despre_viziune_titlu', 'label' => 'Titlu Viziune',  'type' => 'text',     'default_value' => 'VIZIUNE'],
            ['key' => 'field_d_viziune_text',  'name' => 'despre_viziune_text',  'label' => 'Text Viziune',   'type' => 'textarea', 'rows' => 4, 'default_value' => 'Să devenim cea mai respectată academie de Ju-Jitsu din România, formând următorii campioni mondiali.'],

            ['key' => 'field_d_tab_stats', 'label' => 'STATISTICI', 'type' => 'tab', 'placement' => 'left'],
            ['key' => 'field_d_stats', 'name' => 'despre_stats', 'label' => 'Statistici (bara galbenă)', 'type' => 'repeater', 'button_label' => 'Adaugă', 'layout' => 'table', 'sub_fields' => [
                ['key' => 'field_d_stat_numar', 'label' => 'Număr',    'name' => 'numar', 'type' => 'number', 'required' => 1],
                ['key' => 'field_d_stat_sufix', 'label' => 'Sufix',    'name' => 'sufix', 'type' => 'text'],
                ['key' => 'field_d_stat_label', 'label' => 'Etichetă', 'name' => 'label', 'type' => 'text', 'required' => 1],
            ]],

            ['key' => 'field_d_tab_valori', 'label' => 'VALORI', 'type' => 'tab', 'placement' => 'left'],
            ['key' => 'field_d_valori_titlu',    'name' => 'despre_valori_titlu',    'label' => 'Titlu',    'type' => 'text',     'default_value' => 'VALORI|FUNDAMENTALE'],
            ['key' => 'field_d_valori_subtitlu', 'name' => 'despre_valori_subtitlu', 'label' => 'Subtitlu', 'type' => 'textarea', 'rows' => 2, 'default_value' => 'Principiile care ne ghidează în fiecare antrenament și competiție.'],
            ['key' => 'field_d_valori', 'name' => 'despre_valori', 'label' => 'Valori', 'type' => 'repeater', 'button_label' => 'Adaugă valoare', 'layout' => 'block', 'sub_fields' => [
                ['key' => 'field_d_val_kanji',     'label' => 'Kanji',     'name' => 'kanji',     'type' => 'text', 'required' => 1],
                ['key' => 'field_d_val_romaji',    'label' => 'Romaji',    'name' => 'romaji',    'type' => 'text', 'required' => 1],
                ['key' => 'field_d_val_nume',     'label' => 'Nume',     'name' => 'nume',     'type' => 'text'],
                ['key' => 'field_d_val_descriere', 'label' => 'Descriere', 'name' => 'descriere', 'type' => 'textarea', 'rows' => 3, 'required' => 1],
            ]],

            ['key' => 'field_d_tab_timeline', 'label' => 'MOMENTE CHEIE', 'type' => 'tab', 'placement' => 'left'],
            ['key' => 'field_d_timeline_titlu', 'name' => 'despre_timeline_titlu', 'label' => 'Titlu', 'type' => 'text', 'default_value' => 'MOMENTE|CHEIE'],
            ['key' => 'field_d_timeline', 'name' => 'despre_timeline', 'label' => 'Etape', 'type' => 'repeater', 'button_label' => 'Adaugă moment', 'layout' => 'row', 'sub_fields' => [
                ['key' => 'field_d_tl_an',         'label' => 'An',         'name' => 'an',         'type' => 'text', 'required' => 1, 'instructions' => 'Ex: „2008", „2008-2010"'],
                ['key' => 'field_d_tl_eveniment',  'label' => 'Eveniment',  'name' => 'eveniment',  'type' => 'text', 'required' => 1],
                ['key' => 'field_d_tl_descriere',  'label' => 'Descriere',  'name' => 'descriere',  'type' => 'textarea', 'rows' => 2],
            ]],

            ['key' => 'field_d_tab_echipa', 'label' => 'ECHIPA', 'type' => 'tab', 'placement' => 'left'],
            ['key' => 'field_d_echipa_titlu',  'name' => 'despre_echipa_titlu',  'label' => 'Titlu',  'type' => 'text', 'default_value' => 'ECHIPA|KOKORO'],
            ['key' => 'field_d_echipa_text',   'name' => 'despre_echipa_text',   'label' => 'Text introductiv', 'type' => 'textarea', 'rows' => 2, 'default_value' => 'Antrenori dedicați, cu zeci de ani de experiență combinată.'],
            ['key' => 'field_d_echipa_limit',  'name' => 'despre_echipa_limit',  'label' => 'Câți antrenori', 'type' => 'number', 'default_value' => 4, 'min' => 0, 'max' => 12, 'instructions' => '0 = ascunde secțiunea. Antrenorii vin din CPT, sortați după menu_order.'],

            ['key' => 'field_d_tab_cta', 'label' => 'CTA', 'type' => 'tab', 'placement' => 'left'],
            ['key' => 'field_d_cta_titlu', 'name' => 'despre_cta_titlu', 'label' => 'Titlu',         'type' => 'text', 'default_value' => 'ALĂTURĂ-TE|FAMILIEI KOKORO'],
            ['key' => 'field_d_cta_text',  'name' => 'despre_cta_text',  'label' => 'Text',          'type' => 'textarea', 'rows' => 2, 'default_value' => 'Vino la o lecție demonstrativă gratuită și descoperă spiritul Kokoro.'],
            ['key' => 'field_d_cta_buton', 'name' => 'despre_cta_buton', 'label' => 'Text buton',    'type' => 'text', 'default_value' => 'Înscrie-te Acum'],
        ],
        'location' => [
            [['param' => 'page_template', 'operator' => '==', 'value' => 'page-despre-noi.php']],
        ],
        'menu_order' => 0,
        'position'   => 'normal',
        'style'      => 'default',
        'label_placement' => 'top',
        'active'     => true,
    ]);

    acf_add_local_field_group([
        'key'    => 'group_kokoro_pagina_campioni',
        'title'  => 'Conținut pagina Campioni',
        'fields' => [
            [
                'key'           => 'field_campioni_hero_titlu',
                'label'         => 'Titlu hero',
                'name'          => 'campioni_hero_titlu',
                'type'          => 'text',
                'default_value' => 'PERFORMANȚĂ MONDIALĂ',
                'instructions'  => 'Separă cuvântul din italic prin pipe. Ex: "PERFORMANȚĂ|MONDIALĂ" → "PERFORMANȚĂ" normal, "MONDIALĂ" italic.',
            ],
            [
                'key'           => 'field_campioni_hero_subtitlu',
                'label'         => 'Subtitlu hero',
                'name'          => 'campioni_hero_subtitlu',
                'type'          => 'textarea',
                'rows'          => 3,
                'default_value' => 'De la înființare, sportivii Kokoro Brașov au cucerit sute de medalii la competiții naționale și internaționale.',
            ],
            [
                'key'           => 'field_campioni_stats',
                'label'         => 'Statistici (bara galbenă)',
                'name'          => 'campioni_stats',
                'type'          => 'repeater',
                'instructions'  => 'Recomandat 4 statistici.',
                'button_label'  => 'Adaugă statistică',
                'layout'        => 'table',
                'min'           => 0,
                'max'           => 6,
                'sub_fields'    => [
                    [
                        'key'      => 'field_stat_numar',
                        'label'    => 'Număr',
                        'name'     => 'numar',
                        'type'     => 'number',
                        'required' => 1,
                    ],
                    [
                        'key'          => 'field_stat_sufix',
                        'label'        => 'Sufix',
                        'name'         => 'sufix',
                        'type'         => 'text',
                        'instructions' => 'Ex: "+", "K+". Opțional.',
                    ],
                    [
                        'key'      => 'field_stat_label',
                        'label'    => 'Etichetă',
                        'name'     => 'label',
                        'type'     => 'text',
                        'required' => 1,
                    ],
                ],
            ],
            [
                'key'           => 'field_campioni_palmares_note',
                'label'         => 'Notă sub tabelul de palmares',
                'name'          => 'campioni_palmares_note',
                'type'          => 'textarea',
                'rows'          => 2,
                'default_value' => 'Tabelul include doar o selecție a rezultatelor. Palmaresul complet este disponibil la cerere.',
            ],
        ],
        'location' => [
            [
                ['param' => 'page_template', 'operator' => '==', 'value' => 'page-campioni.php'],
            ],
        ],
        'menu_order'      => 0,
        'position'        => 'normal',
        'style'           => 'default',
        'label_placement' => 'top',
        'active'          => true,
    ]);

    acf_add_local_field_group([
        'key'    => 'group_kokoro_pagina_orar',
        'title'  => 'Conținut pagina Orar',
        'fields' => [
            [
                'key'           => 'field_orar_hero_titlu',
                'label'         => 'Titlu hero',
                'name'          => 'orar_hero_titlu',
                'type'          => 'text',
                'default_value' => 'PROGRAMUL|ANTRENAMENTELOR',
                'instructions'  => 'Foloseste pipe "|" pentru a separa pe linii. Linia 2, 4, ... apare cu italic.',
            ],
            [
                'key'           => 'field_orar_hero_subtitlu',
                'label'         => 'Subtitlu hero',
                'name'          => 'orar_hero_subtitlu',
                'type'          => 'textarea',
                'rows'          => 3,
                'default_value' => 'Alege grupa și orele care ți se potrivesc. Antrenamentele au loc în sala Kokoro din Brașov.',
            ],
            [
                'key'           => 'field_orar_legenda',
                'label'         => 'Legendă grupe',
                'name'          => 'orar_legenda',
                'type'          => 'repeater',
                'instructions'  => 'Afișată deasupra tabelului. Recomandat 3 grupe.',
                'button_label'  => 'Adaugă grupă',
                'layout'        => 'table',
                'sub_fields'    => [
                    [
                        'key'      => 'field_legenda_slug',
                        'label'    => 'Slug CSS',
                        'name'     => 'slug',
                        'type'     => 'select',
                        'choices'  => $grupa_choices,
                        'required' => 1,
                        'default_value' => 'copii',
                    ],
                    [
                        'key'      => 'field_legenda_nume',
                        'label'    => 'Nume afișat',
                        'name'     => 'nume',
                        'type'     => 'text',
                        'required' => 1,
                    ],
                    [
                        'key'   => 'field_legenda_varsta',
                        'label' => 'Vârstă / descriere',
                        'name'  => 'varsta',
                        'type'  => 'text',
                    ],
                ],
            ],
            [
                'key'           => 'field_orar_program',
                'label'         => 'Program săptămânal',
                'name'          => 'orar_program',
                'type'          => 'repeater',
                'instructions'  => 'Un rând = un antrenament. Sistemul grupează automat intrările după zi (indiferent de ordine).',
                'button_label'  => 'Adaugă antrenament',
                'layout'        => 'row',
                'sub_fields'    => [
                    [
                        'key'      => 'field_program_zi',
                        'label'    => 'Zi',
                        'name'     => 'zi',
                        'type'     => 'select',
                        'choices'  => $zile_choices,
                        'required' => 1,
                        'default_value' => 'Luni',
                    ],
                    [
                        'key'      => 'field_program_ora',
                        'label'    => 'Oră',
                        'name'     => 'ora',
                        'type'     => 'text',
                        'required' => 1,
                        'instructions' => 'Ex: "17:00 – 18:00"',
                    ],
                    [
                        'key'      => 'field_program_disciplina',
                        'label'    => 'Disciplină',
                        'name'     => 'disciplina',
                        'type'     => 'text',
                        'required' => 1,
                        'instructions' => 'Ex: "Ju-Jitsu", "TRX Suspension", "Ju-Jitsu Autoapărare"',
                    ],
                    [
                        'key'      => 'field_program_grupa',
                        'label'    => 'Grupă',
                        'name'     => 'grupa',
                        'type'     => 'select',
                        'choices'  => $grupa_choices,
                        'default_value' => 'adulti',
                    ],
                    [
                        'key'   => 'field_program_antrenor',
                        'label' => 'Antrenor',
                        'name'  => 'antrenor',
                        'type'  => 'text',
                    ],
                ],
            ],
            [
                'key'           => 'field_orar_nota',
                'label'         => 'Notă sub tabel',
                'name'          => 'orar_nota',
                'type'          => 'textarea',
                'rows'          => 3,
                'default_value' => 'Programul poate suferi modificări în perioada competițiilor sau vacanțelor. Verifică pagina de Facebook sau contactează-ne pentru confirmarea orelor.',
            ],
            [
                'key'           => 'field_orar_cta_titlu',
                'label'         => 'Titlu CTA (jos de tot)',
                'name'          => 'orar_cta_titlu',
                'type'          => 'text',
                'default_value' => 'ALEGE|GRUPA|TA',
                'instructions'  => 'Pipe "|" împarte în segmente; segmentele pare (2, 4, ...) apar italic. "ALEGE|GRUPA|TA" → ALEGE *GRUPA* TA.',
            ],
            [
                'key'           => 'field_orar_cta_text',
                'label'         => 'Text CTA',
                'name'          => 'orar_cta_text',
                'type'          => 'textarea',
                'rows'          => 2,
                'default_value' => 'Prima lecție este gratuită. Vino și descoperă Ju-Jitsu la Kokoro!',
            ],
        ],
        'location' => [
            [
                ['param' => 'page_template', 'operator' => '==', 'value' => 'page-orar.php'],
            ],
        ],
        'menu_order'      => 0,
        'position'        => 'normal',
        'style'           => 'default',
        'label_placement' => 'top',
        'active'          => true,
    ]);

    acf_add_local_field_group([
        'key'    => 'group_kokoro_pagina_tarife',
        'title'  => 'Conținut pagina Tarife',
        'fields' => [
            [
                'key'           => 'field_tarife_hero_titlu',
                'label'         => 'Titlu hero',
                'name'          => 'tarife_hero_titlu',
                'type'          => 'text',
                'default_value' => 'INVESTIȚIA ÎN|PERFORMANȚĂ',
            ],
            [
                'key'           => 'field_tarife_hero_subtitlu',
                'label'         => 'Subtitlu hero',
                'name'          => 'tarife_hero_subtitlu',
                'type'          => 'textarea',
                'rows'          => 3,
                'default_value' => 'Alege pachetul potrivit pentru tine sau copilul tău. Toate abonamentele includ acces la echipament și ghidare personalizată.',
            ],
            [
                'key'           => 'field_tarife_pachete',
                'label'         => 'Pachete',
                'name'          => 'tarife_pachete',
                'type'          => 'repeater',
                'instructions'  => 'Recomandat 3 pachete.',
                'button_label'  => 'Adaugă pachet',
                'layout'        => 'block',
                'sub_fields'    => [
                    [
                        'key'      => 'field_pachet_titlu',
                        'label'    => 'Titlu pachet',
                        'name'     => 'titlu',
                        'type'     => 'text',
                        'required' => 1,
                        'instructions' => 'Ex: „Copii", „Juniori & Adulți", „Personal Training"',
                    ],
                    [
                        'key'      => 'field_pachet_pret',
                        'label'    => 'Preț (doar numărul)',
                        'name'     => 'pret',
                        'type'     => 'number',
                        'required' => 1,
                    ],
                    [
                        'key'           => 'field_pachet_moneda',
                        'label'         => 'Moneda',
                        'name'          => 'moneda',
                        'type'          => 'text',
                        'default_value' => 'lei',
                    ],
                    [
                        'key'           => 'field_pachet_perioada',
                        'label'         => 'Perioadă',
                        'name'          => 'perioada',
                        'type'          => 'text',
                        'default_value' => '/ lună',
                        'instructions'  => 'Ex: „/ lună", „/ ședință", „/ an"',
                    ],
                    [
                        'key'          => 'field_pachet_featured',
                        'label'        => 'Pachet recomandat (evidențiat)',
                        'name'         => 'featured',
                        'type'         => 'true_false',
                        'ui'           => 1,
                        'ui_on_text'   => 'Da',
                        'ui_off_text'  => 'Nu',
                        'instructions' => 'Bifează maxim unul. Va fi evidențiat cu style-ul „featured".',
                    ],
                    [
                        'key'          => 'field_pachet_beneficii',
                        'label'        => 'Beneficii (listă)',
                        'name'         => 'beneficii',
                        'type'         => 'repeater',
                        'button_label' => 'Adaugă beneficiu',
                        'layout'       => 'table',
                        'sub_fields'   => [
                            [
                                'key'      => 'field_beneficiu_text',
                                'label'    => 'Text',
                                'name'     => 'text',
                                'type'     => 'text',
                                'required' => 1,
                            ],
                        ],
                    ],
                    [
                        'key'           => 'field_pachet_buton_text',
                        'label'         => 'Text buton',
                        'name'          => 'buton_text',
                        'type'          => 'text',
                        'default_value' => 'Înscrie-te',
                    ],
                    [
                        'key'           => 'field_pachet_buton_url',
                        'label'         => 'URL buton',
                        'name'          => 'buton_url',
                        'type'          => 'url',
                        'instructions'  => 'Lasă gol pentru a folosi /inscriere/ automat.',
                    ],
                ],
            ],
            [
                'key'           => 'field_tarife_nota',
                'label'         => 'Notă sub pachete',
                'name'          => 'tarife_nota',
                'type'          => 'textarea',
                'rows'          => 3,
                'default_value' => 'Prețurile sunt orientative și pot varia. Pentru tarife actualizate și oferte speciale pentru frați sau grupe, contactează-ne direct.',
            ],
            [
                'key'           => 'field_tarife_cta_titlu',
                'label'         => 'Titlu CTA (jos)',
                'name'          => 'tarife_cta_titlu',
                'type'          => 'text',
                'default_value' => 'PRIMA LECȚIE|E GRATUITĂ',
            ],
            [
                'key'           => 'field_tarife_cta_text',
                'label'         => 'Text CTA',
                'name'          => 'tarife_cta_text',
                'type'          => 'textarea',
                'rows'          => 2,
                'default_value' => 'Vino la o lecție demonstrativă gratuită ca să vezi cum decurge un antrenament Kokoro.',
            ],
            [
                'key'           => 'field_tarife_cta_buton',
                'label'         => 'Text buton CTA',
                'name'          => 'tarife_cta_buton',
                'type'          => 'text',
                'default_value' => 'Programează Lecția Gratuită',
            ],
        ],
        'location' => [
            [
                ['param' => 'page_template', 'operator' => '==', 'value' => 'page-tarife.php'],
            ],
        ],
        'menu_order'      => 0,
        'position'        => 'normal',
        'style'           => 'default',
        'label_placement' => 'top',
        'active'          => true,
    ]);

    acf_add_local_field_group([
        'key'    => 'group_kokoro_pagina_discipline',
        'title'  => 'Conținut pagina Discipline',
        'fields' => [
            [
                'key'           => 'field_discipline_hero_titlu',
                'label'         => 'Titlu hero',
                'name'          => 'discipline_hero_titlu',
                'type'          => 'text',
                'default_value' => 'ARTA|LUPTEI|NOBILE',
            ],
            [
                'key'           => 'field_discipline_hero_subtitlu',
                'label'         => 'Subtitlu hero',
                'name'          => 'discipline_hero_subtitlu',
                'type'          => 'textarea',
                'rows'          => 3,
                'default_value' => 'De la Ju-Jitsu competițional la autoapărare și pregătire fizică — descoperă disciplinele Kokoro Brașov Academy.',
            ],
            [
                'key'           => 'field_discipline_jp_kanji',
                'label'         => 'Citat japonez - kanji',
                'name'          => 'discipline_jp_kanji',
                'type'          => 'text',
                'default_value' => '「柔よく剛を制す」',
            ],
            [
                'key'           => 'field_discipline_jp_romaji',
                'label'         => 'Citat japonez - romaji',
                'name'          => 'discipline_jp_romaji',
                'type'          => 'text',
                'default_value' => 'Ju yoku go wo seisu',
            ],
            [
                'key'           => 'field_discipline_jp_traducere',
                'label'         => 'Citat japonez - traducere',
                'name'          => 'discipline_jp_traducere',
                'type'          => 'text',
                'default_value' => 'Blândețea controlează duritatea — filozofia Ju-Jitsu',
            ],
            [
                'key'           => 'field_discipline_arata_centuri',
                'label'         => 'Arată secțiunea Centuri',
                'name'          => 'discipline_arata_centuri',
                'type'          => 'true_false',
                'ui'            => 1,
                'ui_on_text'    => 'Da',
                'ui_off_text'   => 'Nu',
                'default_value' => 1,
            ],
            [
                'key'           => 'field_discipline_cta_titlu',
                'label'         => 'Titlu CTA',
                'name'          => 'discipline_cta_titlu',
                'type'          => 'text',
                'default_value' => 'ALEGE|DISCIPLINA|TA',
            ],
            [
                'key'           => 'field_discipline_cta_text',
                'label'         => 'Text CTA',
                'name'          => 'discipline_cta_text',
                'type'          => 'textarea',
                'rows'          => 2,
                'default_value' => 'Nu știi ce ți se potrivește? Vino la o lecție demonstrativă gratuită și descoperă!',
            ],
            [
                'key'           => 'field_discipline_cta_buton',
                'label'         => 'Text buton CTA',
                'name'          => 'discipline_cta_buton',
                'type'          => 'text',
                'default_value' => 'Programează Lecția Gratuită',
            ],
        ],
        'location' => [
            [
                ['param' => 'page_template', 'operator' => '==', 'value' => 'page-discipline.php'],
            ],
        ],
        'menu_order'      => 0,
        'position'        => 'normal',
        'style'           => 'default',
        'label_placement' => 'top',
        'active'          => true,
    ]);

    acf_add_local_field_group([
        'key'    => 'group_kokoro_pagina_galerie',
        'title'  => 'Conținut pagina Galerie',
        'fields' => [
            [
                'key'           => 'field_galerie_hero_titlu',
                'label'         => 'Titlu hero',
                'name'          => 'galerie_hero_titlu',
                'type'          => 'text',
                'default_value' => 'MOMENTE|KOKORO',
            ],
            [
                'key'           => 'field_galerie_hero_subtitlu',
                'label'         => 'Subtitlu hero',
                'name'          => 'galerie_hero_subtitlu',
                'type'          => 'textarea',
                'rows'          => 3,
                'default_value' => 'Antrenamente, competiții, tabere și momente de bucurie — viața la Kokoro Brașov Academy în imagini.',
            ],
            [
                'key'           => 'field_galerie_imagini',
                'label'         => 'Imagini',
                'name'          => 'galerie_imagini',
                'type'          => 'repeater',
                'instructions'  => 'Adaugă imagini una câte una. Folosește „Add Row" sau trage-le în ordine.',
                'button_label'  => 'Adaugă imagine',
                'layout'        => 'block',
                'sub_fields'    => [
                    [
                        'key'           => 'field_galerie_imagine',
                        'label'         => 'Imagine',
                        'name'          => 'imagine',
                        'type'          => 'image',
                        'return_format' => 'array',
                        'preview_size'  => 'medium',
                        'required'      => 1,
                    ],
                    [
                        'key'   => 'field_galerie_caption',
                        'label' => 'Caption (opțional)',
                        'name'  => 'caption',
                        'type'  => 'text',
                    ],
                ],
            ],
            [
                'key'           => 'field_galerie_cta_text',
                'label'         => 'Text sub galerie',
                'name'          => 'galerie_cta_text',
                'type'          => 'textarea',
                'rows'          => 2,
                'default_value' => 'Mai multe fotografii și videoclipuri pe pagina noastră de Facebook.',
            ],
            [
                'key'           => 'field_galerie_cta_buton',
                'label'         => 'Text buton',
                'name'          => 'galerie_cta_buton',
                'type'          => 'text',
                'default_value' => 'Vezi pe Facebook',
            ],
            [
                'key'           => 'field_galerie_cta_url',
                'label'         => 'URL buton',
                'name'          => 'galerie_cta_url',
                'type'          => 'url',
                'default_value' => 'https://www.facebook.com/kokorobrasovacademy',
            ],
        ],
        'location' => [
            [
                ['param' => 'page_template', 'operator' => '==', 'value' => 'page-galerie.php'],
            ],
        ],
        'menu_order'      => 0,
        'position'        => 'normal',
        'style'           => 'default',
        'label_placement' => 'top',
        'active'          => true,
    ]);
}
add_action('acf/init', 'kokoro_acf_register_page_templates');
